# Generated by Django 2.1.4 on 2018-12-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
